version: '3.8'

services:
  # Vector for collecting and processing telemetry
  vector:
    image: timberio/vector:0.34-alpine
    ports:
      - "4318:4318"  # OTLP HTTP endpoint
      - "8686:8686"  # Vector API (optional)
    volumes:
      - ./vector-simple.toml:/etc/vector/vector.toml:ro
      - ./telemetry-output:/var/lib/vector
    environment:
      - VECTOR_LOG=info
    command: ["--config", "/etc/vector/vector.toml"]

  # Optional: Jaeger for visualization
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"     # OTLP gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true