name: Notepad Automation Workflow
description: Automate Notepad text editing using Python

steps:
  - id: run_notepad_automation
    tool_name: run_command
    arguments:
      engine: "python"
      script_file: "./notepad_automation.py"
    delay: 1s

  - id: display_results
    tool_name: run_command
    arguments:
      engine: "javascript"
      run: |
        const result = run_notepad_automation_result;
        const status = run_notepad_automation_status;
        
        console.log(`Notepad automation status: ${status}`);
        
        if (status === 'success' && result) {
          console.log("=== Notepad Automation Results ===");
          console.log(`Status: ${result.status}`);
          console.log(`Message: ${result.message}`);
          
          if (result.actions_performed) {
            console.log("\nActions performed:");
            result.actions_performed.forEach(action => {
              console.log(`  ✓ ${action}`);
            });
          }
          
          if (result.text_length) {
            console.log(`\nText length: ${result.text_length} characters`);
          }
          
          return { automation_complete: true };
        } else {
          console.log("Notepad automation failed");
          return { automation_complete: false };
        }