name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build workspace
        run: cargo build --workspace --verbose
      # - name: Run tests
      #   run: cargo test --workspace --verbose


