name: Publish NPM Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        settings:
          # - host: ubuntu-latest
          #   target: x86_64-unknown-linux-gnu
          #   docker: |
          #     docker run --rm -v ~/.cargo/git:/usr/local/cargo/git -v ~/.cargo/registry:/usr/local/cargo/registry -v $(pwd):/build -w /build node:18-slim sh -c "apt update && apt install -y build-essential && npm run build"
          #   build: |
          #     cd bindings/nodejs
          #     npm run build
          #     cp terminator.linux-x64-gnu.node npm/linux-x64-gnu/
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            build: |
              cd bindings/nodejs
              npm run build  
              cp terminator.win32-x64-msvc.node npm/win32-x64-msvc/
          # - host: macos-latest
          #   target: x86_64-apple-darwin
          #   build: |
          #     cd bindings/nodejs
          #     npm run build
          #     cp terminator.darwin-x64.node npm/darwin-x64/
          # - host: macos-latest
          #   target: aarch64-apple-darwin
          #   build: |
          #     cd bindings/nodejs
          #     npm run build
          #     cp terminator.darwin-arm64.node npm/darwin-arm64/

    name: stable - ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.settings.target }}-cargo-registry

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ matrix.settings.target }}-cargo-index

      - name: Install dependencies
        run: |
          cd bindings/nodejs
          npm ci

      - name: Sync version
        run: |
          cd bindings/nodejs
          npm run sync-version

      - name: Build
        run: ${{ matrix.settings.build }}
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: bindings/nodejs/npm/*/

  publish:
    name: Publish NPM packages
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Copy artifacts to npm packages
        run: |
          cp -r artifacts/bindings-*/npm/* bindings/nodejs/npm/

      - name: Publish platform packages
        run: |
          cd bindings/nodejs
          for dir in npm/*/; do
            if [ -d "$dir" ] && [ -f "$dir/package.json" ]; then
              echo "Publishing $(basename "$dir")"
              cd "$dir"
              npm publish --access public || echo "Package already published or failed"
              cd ../..
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish main package
        run: |
          cd bindings/nodejs
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
