name: Test OpenTelemetry Integration

on:
  push:
    branches: [ main, feature/opentelemetry-integration ]
  pull_request:
    branches: [ main ]
    paths:
      - 'terminator-mcp-agent/**'
      - 'tests/**'
      - '.github/workflows/test-telemetry.yml'

jobs:
  test-telemetry:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Cache Cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache Node dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    
    - name: Install dependencies
      run: |
        npm ci
        cargo build --workspace
    
    - name: Test without telemetry feature
      run: |
        echo "Testing build without telemetry feature..."
        cargo build -p terminator-mcp-agent
        cargo test -p terminator-mcp-agent
    
    - name: Test with telemetry feature
      run: |
        echo "Testing build with telemetry feature..."
        cargo build -p terminator-mcp-agent --features telemetry
        cargo test -p terminator-mcp-agent --features telemetry
    
    - name: Start mock OTLP collector
      run: |
        # Start a simple mock collector in background
        node tests/integration/test-http-events.js &
        echo $! > collector.pid
        sleep 2
    
    - name: Integration test with telemetry enabled
      env:
        OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4318
      run: |
        # Build and run MCP agent with telemetry
        cargo build -p terminator-mcp-agent --features telemetry
        
        # Run integration tests
        node tests/integration/test-otel-integration.js
    
    - name: Integration test with telemetry disabled
      env:
        OTEL_SDK_DISABLED: true
      run: |
        # Run with telemetry disabled via env var
        cargo run -p terminator-mcp-agent --features telemetry -- --transport http --port 3001 &
        echo $! > agent.pid
        sleep 3
        
        # Verify no telemetry is sent
        curl -f http://localhost:3001/health || true
        
        # Cleanup
        kill $(cat agent.pid) || true
    
    - name: Cleanup
      if: always()
      run: |
        kill $(cat collector.pid) || true
        kill $(cat agent.pid) || true
    
    - name: Lint check
      run: |
        cargo fmt -p terminator-mcp-agent -- --check
        cargo clippy -p terminator-mcp-agent --features telemetry -- -D warnings